export const mockFirm = {
  id: "firm-1",
  name: "Smith & Associates LLP",
  email: "contact@smithassociates.com",
  phone: "555-0199",
  address: "123 Legal Way, Suite 400, New York, NY 10001",
  taxId: "12-3456789",
  require2fa: false,
  sessionTimeout: 60,
  dataRetention: "30",
  createdAt: new Date("2020-01-01T00:00:00Z"),
  updatedAt: new Date("2026-08-01T00:00:00Z"),
};

export const mockUser = {
  id: "user-1",
  firstName: "Harvey",
  lastName: "Specter",
  email: "harvey@smithassociates.com",
  phone: "555-0100",
  passwordHash: "mocked-hash",
  role: "MANAGING_PARTNER",
  isActive: true,
  firmId: mockFirm.id,
  managingPartnerId: null,
  attorneyId: null,
  createdAt: new Date("2020-01-01T00:00:00Z"),
  updatedAt: new Date("2026-08-01T00:00:00Z"),
};

export const mockUsers = [
  {
    id: "user-0",
    firstName: "System",
    lastName: "Admin",
    email: "admin@lexvalue.com",
    phone: "555-0000",
    passwordHash: "mocked-hash",
    role: "ADMIN",
    isActive: true,
    firmId: mockFirm.id,
    managingPartnerId: null,
    attorneyId: null,
    createdAt: new Date("2020-01-01T00:00:00Z"),
    updatedAt: new Date("2026-08-01T00:00:00Z"),
  },
  mockUser,
  {
    id: "user-2",
    firstName: "Mike",
    lastName: "Ross",
    email: "mike@smithassociates.com",
    phone: "555-0101",
    passwordHash: "mocked-hash",
    role: "ATTORNEY",
    isActive: true,
    firmId: mockFirm.id,
    managingPartnerId: mockUser.id,
    attorneyId: null,
    createdAt: new Date("2021-05-15T00:00:00Z"),
    updatedAt: new Date("2026-08-01T00:00:00Z"),
  },
  {
    id: "user-3",
    firstName: "Rachel",
    lastName: "Zane",
    email: "rachel@smithassociates.com",
    phone: "555-0102",
    passwordHash: "mocked-hash",
    role: "PARALEGAL",
    isActive: true,
    firmId: mockFirm.id,
    managingPartnerId: null,
    attorneyId: "user-2",
    createdAt: new Date("2022-03-10T00:00:00Z"),
    updatedAt: new Date("2026-08-01T00:00:00Z"),
  },
];

export const mockCases = [
  {
    id: "case-1",
    referenceId: "LVA-2026-001",
    title: "Johnson Medical Malpractice",
    client: "Sarah Johnson",
    clientEmail: "sarah.j@example.com",
    clientPhone: "555-0123",
    clientAge: 45,
    clientGender: "Female",
    clientAddress: "456 Oak St, Brooklyn, NY 11201",
    type: "Medical Malpractice",
    dateOfInjury: new Date("2025-11-15T00:00:00Z"),
    status: "ACTIVE",
    flags: 2,
    customPrompt: null,
    approvalStatus: "APPROVED",
    rejectionReason: null,
    scanProgress: 100,
    scanStage: "COMPLETED",
    firmId: mockFirm.id,
    createdByUserId: mockUser.id,
    createdAt: new Date("2026-01-10T10:00:00Z"),
    updatedAt: new Date("2026-08-10T15:30:00Z"),
    documents: [],
    assignedUsers: [mockUser, mockUsers[1]],
  },
  {
    id: "case-2",
    referenceId: "LVA-2026-002",
    title: "Williams Auto Collision",
    client: "Marcus Williams",
    clientEmail: "marcus.w@example.com",
    clientPhone: "555-0144",
    clientAge: 32,
    clientGender: "Male",
    clientAddress: "789 Pine Ave, Queens, NY 11101",
    type: "Personal Injury",
    dateOfInjury: new Date("2026-04-20T00:00:00Z"),
    status: "REVIEWING",
    flags: 0,
    customPrompt: "Focus on whiplash and spinal injuries.",
    approvalStatus: "PENDING",
    rejectionReason: null,
    scanProgress: 45,
    scanStage: "PROCESSING",
    firmId: mockFirm.id,
    createdByUserId: mockUsers[1].id,
    createdAt: new Date("2026-07-25T09:15:00Z"),
    updatedAt: new Date("2026-08-12T11:20:00Z"),
    documents: [],
    assignedUsers: [mockUsers[1], mockUsers[2]],
  },
  {
    id: "case-3",
    referenceId: "LVA-2026-003",
    title: "Davis Workplace Slip & Fall",
    client: "Emily Davis",
    clientEmail: "emily.d@example.com",
    clientPhone: "555-0167",
    clientAge: 58,
    clientGender: "Female",
    clientAddress: "321 Cedar Rd, Bronx, NY 10451",
    type: "Workers Compensation",
    dateOfInjury: new Date("2026-02-05T00:00:00Z"),
    status: "CLOSED",
    flags: 0,
    customPrompt: null,
    approvalStatus: "APPROVED",
    rejectionReason: null,
    scanProgress: 100,
    scanStage: "COMPLETED",
    firmId: mockFirm.id,
    createdByUserId: mockUser.id,
    createdAt: new Date("2026-03-01T14:45:00Z"),
    updatedAt: new Date("2026-06-30T16:00:00Z"),
    documents: [],
    assignedUsers: [mockUser],
  },
];

export const mockDocuments = [
  {
    id: "doc-1",
    fileName: "Medical_Records_Johnson.pdf",
    s3Key: "mock-s3-key-1.pdf",
    size: 2500000,
    mimeType: "application/pdf",
    status: "READY",
    summary: "Comprehensive medical history and injury report from General Hospital.",
    aiAnalysis: { findings: ["Fractured femur", "Internal bleeding"] },
    caseId: "case-1",
    firmId: mockFirm.id,
    createdAt: new Date("2026-01-12T11:00:00Z"),
    updatedAt: new Date("2026-01-12T11:05:00Z"),
  },
  {
    id: "doc-2",
    fileName: "Police_Report_Williams.pdf",
    s3Key: "mock-s3-key-2.pdf",
    size: 850000,
    mimeType: "application/pdf",
    status: "PROCESSING",
    summary: null,
    aiAnalysis: null,
    caseId: "case-2",
    firmId: mockFirm.id,
    createdAt: new Date("2026-08-12T11:15:00Z"),
    updatedAt: new Date("2026-08-12T11:15:00Z"),
  },
];

export const mockNotifications = [
  {
    id: "notif-1",
    message: "New case 'Williams Auto Collision' requires approval.",
    type: "CASE_CREATED",
    isRead: false,
    userId: mockUser.id,
    firmId: mockFirm.id,
    caseId: "case-2",
    createdAt: new Date("2026-08-12T11:20:00Z"),
  },
  {
    id: "notif-2",
    message: "AI Scan completed for 'Johnson Medical Malpractice'.",
    type: "INFO",
    isRead: true,
    userId: mockUser.id,
    firmId: mockFirm.id,
    caseId: "case-1",
    createdAt: new Date("2026-08-10T15:30:00Z"),
  },
];

export const mockTimelineEvents = [
  {
    id: "event-1",
    date: new Date("2025-11-15T14:30:00Z"),
    title: "Patient Admitted",
    description: "Patient admitted to ER with severe abdominal pain.",
    documentId: "doc-1",
    caseId: "case-1",
    firmId: mockFirm.id,
    createdAt: new Date("2026-01-12T11:05:00Z"),
  },
  {
    id: "event-2",
    date: new Date("2025-11-16T08:00:00Z"),
    title: "Surgery Performed",
    description: "Emergency appendectomy performed by Dr. Smith.",
    documentId: "doc-1",
    caseId: "case-1",
    firmId: mockFirm.id,
    createdAt: new Date("2026-01-12T11:05:00Z"),
  },
];

export const mockAuditLogs = [
  {
    id: "log-1",
    action: "USER_LOGIN",
    details: "Harvey Specter logged in.",
    userId: mockUser.id,
    firmId: mockFirm.id,
    caseId: null,
    createdAt: new Date("2026-08-13T09:00:00Z"),
  },
  {
    id: "log-2",
    action: "CASE_CREATED",
    details: "Marcus Williams case created.",
    userId: mockUsers[1].id,
    firmId: mockFirm.id,
    caseId: "case-2",
    createdAt: new Date("2026-08-12T11:20:00Z"),
  },
];

// Helper functions for easy access
export const getMockUser = () => mockUser;
export const getMockCases = () => mockCases;
export const getMockCaseById = (id: string) => mockCases.find(c => c.id === id);
export const getMockDocumentsForCase = (caseId: string) => mockDocuments.filter(d => d.caseId === caseId);
export const getMockTimelineForCase = (caseId: string) => mockTimelineEvents.filter(t => t.caseId === caseId);
export const getMockNotifications = () => mockNotifications;
export const getMockAuditLogs = () => mockAuditLogs;
export const getMockUsers = () => mockUsers;
export const getMockFirm = () => mockFirm;
